import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "SpaceY",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={`flex flex-col h-screen justify-between`}>
        <section className={`h-500 `}>
          <Header />
        </section>
        <section className={` h-500 `}>{children}</section>
        <Footer className={`h-500 `} />
      </body>
    </html>
  );
}
